### ISSUE TITLE
Snap will not work with credentials

### ISSUE THREAD

**Issue by kz6fittycent** [Kenshiro-28/GDAX-Trading-Bot#3]
Greetings, 

Firstly, thanks for providing this snap and the effort you've put into it is much appreciated!

I am having a problem that is likely user error but wanted to reach out to you to see if it is a bug with the snap or if it's just me.

Per the instructions, I've added my credentials from the API in pro.coinbase.com to `.bashrc` in `/home/$USER`. 

I keep receiving the same error:

```
Connecting to Coinbase Pro in 30 seconds ...



/snap/gdax-trading-bot/12/node_modules/coinbase-pro/lib/utilities.js:17
    throw new Error(
    ^

Error: Invalid or incomplete authentication credentials. Please provide all of the key, secret, and passphrase fields.
    at Object.checkAuth (/snap/gdax-trading-bot/12/node_modules/coinbase-pro/lib/utilities.js:17:11)
    at module.exports.signRequest (/snap/gdax-trading-bot/12/node_modules/coinbase-pro/lib/request_signer.js:17:9)
    at AuthenticatedClient._getSignature (/snap/gdax-trading-bot/12/node_modules/coinbase-pro/lib/clients/authenticated.js:32:17)
    at AuthenticatedClient.request (/snap/gdax-trading-bot/12/node_modules/coinbase-pro/lib/clients/authenticated.js:21:12)
    at AuthenticatedClient.get (/snap/gdax-trading-bot/12/node_modules/coinbase-pro/lib/clients/public.js:23:17)
    at AuthenticatedClient.getAccounts (/snap/gdax-trading-bot/12/node_modules/coinbase-pro/lib/clients/authenticated.js:54:17)
    at Timeout.setInterval [as _onTimeout] (/snap/gdax-trading-bot/12/index.js:401:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

The same error occurs no matter what I try. I have verified that the creds are correct so I'm not sure what else to do.

TIA!

**Comment by kz6fittycent** [comment]
Please see my new [PR](https://github.com/Kenshiro-28/GDAX-Trading-Bot/pull/4).
